// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spymaeryxmwbormuijwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNweW1hZXJ5eG13Ym9ybXVpand0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4MjkyMTMsImV4cCI6MjA4NTQwNTIxM30.ZM8kuzmycsEL2shc8gCamv_d5LAdDoZEZJCgbOB3yvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});