// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbcwtmotraprcbbldfsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiY3d0bW90cmFwcmNiYmxkZnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2NDc5MjEsImV4cCI6MjA4NDIyMzkyMX0.eIEYmxIwv9KXIvUR8dD9z08BXxvougmjF_tYAqrB0fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});